# Generated by Django 5.0.1 on 2026-02-07 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communications.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='authentication.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='messages_recipie_6234cf_idx'), models.Index(fields=['sender', 'sent_at'], name='messages_sender__039ac4_idx'), models.Index(fields=['parent_message'], name='messages_parent__8cda5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('approval_required', 'Approval Required'), ('message_received', 'Message Received'), ('document_shared', 'Document Shared'), ('deadline_approaching', 'Deadline Approaching'), ('status_changed', 'Status Changed'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('petty_cash_approved', 'Petty Cash Approved'), ('petty_cash_rejected', 'Petty Cash Rejected')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='notificatio_related_83c4d7_idx')],
            },
        ),
    ]
