# Generated by Django 5.0.1 on 2026-02-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_add_broadcast_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_is_broa_1c6821_idx',
            old_name='messages_is_broa_idx',
        ),
    ]
