# Generated by Django 5.0.1 on 2026-03-09 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_rename_messages_is_broa_idx_messages_is_broa_1c6821_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('feature_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('new_feature', 'New Feature'), ('improvement', 'Improvement'), ('bug_fix', 'Bug Fix'), ('documentation', 'Documentation')], default='new_feature', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this update in AI context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_updates',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['is_active', 'date'], name='feature_upd_is_acti_3d3ac9_idx')],
            },
        ),
    ]
