# Generated by Django 5.0.1 on 2026-03-11 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_featureupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField(help_text='User message that was classified')),
                ('classification_type', models.CharField(choices=[('Navigation', 'Navigation'), ('Feature_Guide', 'Feature Guide'), ('Company_Data', 'Company Data'), ('Kenya_Governance', 'Kenya Governance'), ('Web_Search', 'Web Search'), ('Tip', 'Tip')], db_index=True, help_text='Classified message type', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score for the classification (0.0-1.0)')),
                ('all_scores', models.JSONField(default=dict, help_text='Confidence scores for all classification types')),
                ('processing_time_ms', models.IntegerField(help_text='Time taken to classify message in milliseconds')),
                ('user_feedback', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partially Correct'), ('none', 'No Feedback')], default='none', help_text='User feedback on classification accuracy', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context used for classification (user role, company, etc.)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classification_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='classificat_timesta_0209bd_idx'), models.Index(fields=['classification_type'], name='classificat_classif_fc9848_idx'), models.Index(fields=['user', 'timestamp'], name='classificat_user_id_6466ae_idx'), models.Index(fields=['confidence_score'], name='classificat_confide_723ba4_idx')],
            },
        ),
    ]
