# Generated by Django 5.0.1 on 2026-03-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_classificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, help_text="User's preferred name for greetings", max_length=100)),
                ('role_context', models.TextField(blank=True, help_text="Context about user's role and responsibilities")),
                ('tone_preference', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('balanced', 'Balanced')], default='balanced', help_text="User's preferred conversational tone", max_length=20)),
                ('last_topics', models.JSONField(default=list, help_text='List of recent conversation topics (max 10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User this memory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Memory',
                'verbose_name_plural': 'Assistant Memories',
                'db_table': 'assistant_memory',
            },
        ),
    ]
