# Generated by Django 5.0.1 on 2026-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_assistantmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_approved', 'Task Approved'), ('task_rejected', 'Task Rejected'), ('approval_required', 'Approval Required'), ('message_received', 'Message Received'), ('document_shared', 'Document Shared'), ('deadline_approaching', 'Deadline Approaching'), ('status_changed', 'Status Changed'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('petty_cash_approved', 'Petty Cash Approved'), ('petty_cash_rejected', 'Petty Cash Rejected'), ('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected')], db_index=True, max_length=50),
        ),
    ]
