# Generated by Django 5.0.1 on 2026-02-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_staff_n_8a8c46_idx',
            old_name='staff_staff_n_68f2c7_idx',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_company_f75939_idx',
            old_name='staff_company_f82024_idx',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_email_090e5f_idx',
            old_name='staff_email_f66e96_idx',
        ),
    ]
