# Generated by Django 5.0.1 on 2026-02-07 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('companies', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('leave', 'Leave Request'), ('expense_reimbursement', 'Expense Reimbursement'), ('purchase', 'Purchase Request'), ('document_approval', 'Document Approval'), ('petty_cash', 'Petty Cash'), ('other', 'Other')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='companies.company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='authentication.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.request')),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['step_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['company', 'status'], name='requests_company_c5487f_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requester', 'status'], name='requests_request_0b77d5_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type', 'status'], name='requests_request_9ff4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['request', 'step_number'], name='approvals_request_ff8e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'status'], name='approvals_approve_3551a3_idx'),
        ),
    ]
