# Generated by Django 5.0.1 on 2026-03-12 10:30

from django.db import migrations


def migrate_task_status_data(apps, schema_editor):
    """
    Migrate existing task status values to new format:
    - 'todo' -> 'pending'
    - 'review' -> 'completed' (assuming review means completed but not approved)
    - 'cancelled' -> 'rejected'
    - Keep 'in_progress' and 'completed' as-is
    """
    Task = apps.get_model('workflows', 'Task')
    
    # Update status values
    status_mapping = {
        'todo': 'pending',
        'review': 'completed',
        'cancelled': 'rejected',
    }
    
    for old_status, new_status in status_mapping.items():
        Task.objects.filter(status=old_status).update(status=new_status)


def reverse_migrate_task_status_data(apps, schema_editor):
    """
    Reverse migration - convert new status values back to old format
    """
    Task = apps.get_model('workflows', 'Task')
    
    # Reverse status mapping
    reverse_mapping = {
        'pending': 'todo',
        'rejected': 'cancelled',
        # Note: 'completed' stays as 'completed', 'approved' becomes 'completed'
    }
    
    for new_status, old_status in reverse_mapping.items():
        Task.objects.filter(status=new_status).update(status=old_status)
    
    # Convert 'approved' back to 'completed'
    Task.objects.filter(status='approved').update(status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_update_task_status_choices'),
    ]

    operations = [
        migrations.RunPython(
            migrate_task_status_data,
            reverse_migrate_task_status_data,
        ),
    ]
