# Generated by Django 5.0.1 on 2026-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_migrate_task_status_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('leave', 'Leave Request'), ('expense_reimbursement', 'Expense Reimbursement'), ('purchase', 'Purchase Request'), ('document_approval', 'Document Approval'), ('document_deletion', 'Document Deletion'), ('petty_cash', 'Petty Cash'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
