# Generated by Django 5.0.1 on 2026-03-16 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_risk_category_company_risk_level'),
        ('staff', '0002_rename_staff_staff_n_68f2c7_idx_staff_staff_n_8a8c46_idx_and_more'),
        ('workflows', '0006_task_started_at_task_total_time_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_leave_entitlement', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_leave_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('maternity_leave_entitlement', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(0)])),
                ('maternity_leave_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paternity_leave_entitlement', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('paternity_leave_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sick_leave_entitlement', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sick_leave_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('emergency_leave_entitlement', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('emergency_leave_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='companies.company')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='staff.staff')),
            ],
            options={
                'db_table': 'leave_balances',
                'indexes': [models.Index(fields=['staff', 'company'], name='leave_balan_staff_i_368e63_idx')],
            },
        ),
    ]
