# Generated by Django 5.0.1 on 2026-02-07 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('companies', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purpose', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], db_index=True, default='draft', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash', to='authentication.userprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_requests', to='companies.company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_requests', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'petty_cash_requests',
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['company', 'status'], name='petty_cash__company_27284f_idx'), models.Index(fields=['requester'], name='petty_cash__request_748a26_idx'), models.Index(fields=['request_date'], name='petty_cash__request_325f5d_idx')],
            },
        ),
    ]
