# Generated by Django 5.0.1 on 2026-02-06 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('report', 'Report'), ('certificate', 'Certificate'), ('correspondence', 'Correspondence'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'category'], name='documents_company_785009_idx'), models.Index(fields=['uploaded_by'], name='documents_uploade_aad805_idx'), models.Index(fields=['is_archived'], name='documents_is_arch_75b4ea_idx')],
            },
        ),
    ]
