# Generated by Django 5.0.1 on 2026-02-11 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('annual-return', 'Annual Return'), ('board-resolution', 'Board Resolution'), ('contract', 'Contract'), ('letter', 'Letter'), ('report', 'Report'), ('form', 'Form'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='templates_categor_05cfe3_idx'), models.Index(fields=['-last_used'], name='templates_last_us_c2bbf1_idx'), models.Index(fields=['-usage_count'], name='templates_usage_c_47fafd_idx')],
            },
        ),
    ]
