# Generated by Django 5.0.1 on 2026-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_subfolder'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_company_785009_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_company_76a70b_idx',
            old_name='documents_company_cat_subfolder_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_company_89d284_idx',
            old_name='documents_company_subfolder_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('sealed', 'Sealed'), ('certified', 'Certified'), ('commissioned', 'Commissioned'), ('notarised', 'Notarised'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('report', 'Report'), ('certificate', 'Certificate'), ('correspondence', 'Correspondence'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
