# Generated by Django 5.0.1 on 2026-02-06 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company')),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_profil_email_8a1024_idx'), models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'), models.Index(fields=['company', 'role'], name='user_profil_company_9c4ad5_idx')],
            },
        ),
    ]
