# Generated by Django 5.0.1 on 2026-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_last_login_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
