# Generated by Django 5.0.1 on 2026-02-06 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tax_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['registration_number'], name='companies_registr_49a0dd_idx'), models.Index(fields=['tax_id'], name='companies_tax_id_cd19d0_idx'), models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx')],
            },
        ),
    ]
