# Generated by Django 5.0.1 on 2026-02-11 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Directors',
                'db_table': 'directors',
                'ordering': ['-appointment_date', 'name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='directors_company_f5ef63_idx'), models.Index(fields=['appointment_date'], name='directors_appoint_f3b302_idx')],
            },
        ),
    ]
