# Generated by Django 5.0.1 on 2026-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='risk_category',
            field=models.CharField(blank=True, default='', help_text='Specific risk category (e.g., retail_clients, financial_institutions)', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_level',
            field=models.CharField(choices=[('level_1', 'Level 1 - Low Risk'), ('level_2', 'Level 2 - Medium Risk'), ('level_3', 'Level 3 - High Risk')], default='level_2', help_text='Risk assessment level for the company', max_length=20),
        ),
    ]
